### ISSUE TITLE
Flutter version doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by WWWWWWhite** [harmonoid/libwinmedia#13]
Hi, 

when I add the following code to the flutter example app

```
void main() {
  LWM.initialize();
  var player = Player(id: 0);
  player.open([
    Media(uri: 'file://home/osboxes/click.mp3'),
  ]);
  player.play();
  
  runApp(const MyApp());
}
```

 I get the following output

```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
libwinmedia - 0.0.3
-------------------
Building on Linux against GTK 3.0 & WebKit2 4.0
C++ Standard: 17
Enabled Dart VM NativePorts callbacks.
Debug service listening on ws://127.0.0.1:39813/B6JZIhK31HU=/ws
Syncing files to device Linux...
WebKit wasn't able to find a WebVTT encoder. Not continuing without platform support for subtitles.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'PlayerErrorCode'
#0      LWM.receivePort.<anonymous closure> (package:libwinmedia/src/internal.dart:113:44)
#1      _rootRunUnary (dart:async/zone.dart:1444:13)
#2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#7      _StreamController._add (dart:async/stream_controller.dart:607:7)
#8      _StreamController.add (dart:async/stream_controller.dart:554:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:187:12)

```

It seems that using libwebkit2gtk-4.0-dev requires WebVTT encoder even for playing sound... ? 

Thank you, 

W

**Comment by alexmercerind** [comment]
@bdlukaa I'm returning `0` on Linux at the moment.
